const MAP_SIZE=160,TILE=40,CORE_RANGE=20,PLAYER_MAX=30;
const BLOCK={WALL:0,DIRT:1,FERTILE:2,WATER:3,CORE:4,HOT:5};
const COLORS={[BLOCK.WALL]:'#555',[BLOCK.DIRT]:'#8B5A2B',[BLOCK.FERTILE]:'#5C4033',[BLOCK.WATER]:'#1E90FF',[BLOCK.CORE]:'#2a2a3a',[BLOCK.HOT]:'#c44a1a'};
const ORE={NONE:0,COPPER:1,LEAD:2,COAL:3,TITANIUM:4,THORIUM:5,METALOM:6};
const ORE_COLORS={[ORE.COPPER]:'#d99d73',[ORE.LEAD]:'#8c7fa9',[ORE.COAL]:'#1a1a1a',[ORE.TITANIUM]:'#8da1b0',[ORE.THORIUM]:'#f9a3c7',[ORE.METALOM]:'#6e6e6e'};
const ORE_TO_ID={[ORE.COPPER]:'copper',[ORE.LEAD]:'lead',[ORE.COAL]:'coal',[ORE.TITANIUM]:'titanium',[ORE.THORIUM]:'thorium',[ORE.METALOM]:'metalom'};
const PLAYER_FORBIDDEN=new Set([ORE.TITANIUM,ORE.THORIUM]);
const DIR={RIGHT:0,DOWN:1,LEFT:2,UP:3};
const DIR_DX=[1,0,-1,0],DIR_DY=[0,1,0,-1];
const DIR_ARROW=['→','↓','←','↑'];
const RESOURCES=[
  {id:'copper',name:'Медь',color:'#d99d73'},{id:'lead',name:'Свинец',color:'#8c7fa9'},{id:'coal',name:'Уголь',color:'#272727'},
  {id:'sand',name:'Песок',color:'#f7cba0'},{id:'titanium',name:'Титан',color:'#8da1b0'},{id:'thorium',name:'Торий',color:'#f9a3c7'},
  {id:'metalom',name:'Металлом',color:'#6e6e6e'},{id:'graphite',name:'Графит',color:'#b0b0b0'},{id:'metaglass',name:'Метастекло',color:'#e8f4f8'},
  {id:'silicon',name:'Кремний',color:'#d4d4c8'},{id:'phase',name:'Фаза',color:'#c77dff'},{id:'surge',name:'Кинет.',color:'#f3e03b'},
  {id:'plastanium',name:'Пластан',color:'#9eff7a'},{id:'spore',name:'Спора',color:'#6bcf5f'},{id:'blast',name:'Взрывн.',color:'#ff6b35'},
  {id:'pyratite',name:'Пиротит',color:'#ff3c00'},{id:'water',name:'Вода',color:'#4da6ff',liquid:true},{id:'slag',name:'Шлак',color:'#ff6a00',liquid:true},
  {id:'oil',name:'Нефть',color:'#2a1a0a',liquid:true},{id:'cryo',name:'Крио',color:'#6ef0ff',liquid:true}
];
let _id=0;
const BTYPE={
  CONVEYOR:_id++,TITANIUM_CONVEYOR:_id++,PLASTANIUM_CONVEYOR:_id++,ARMORED_CONVEYOR:_id++,
  JUNCTION:_id++,BRIDGE:_id++,PHASE_BRIDGE:_id++,ROUTER:_id++,DISTRIBUTOR:_id++,
  SORTER:_id++,INV_SORTER:_id++,GATE:_id++,INV_GATE:_id++,UNLOADER:_id++,MASS_DRIVER:_id++,
  CONTAINER:_id++,VAULT:_id++,
  MECH_DRILL:_id++,PNEU_DRILL:_id++,LASER_DRILL:_id++,AIRBLAST_DRILL:_id++,
  CONDUIT:_id++,PULSE_CONDUIT:_id++,PLATED_CONDUIT:_id++,LIQUID_ROUTER:_id++,LIQUID_JUNCTION:_id++,
  LIQUID_BRIDGE:_id++,PHASE_CONDUIT:_id++,TANK:_id++,LARGE_TANK:_id++,
  MECH_PUMP:_id++,ROTARY_PUMP:_id++,THERMAL_PUMP:_id++,WATER_EXTRACTOR:_id++,OIL_EXTRACTOR:_id++,CULTIVATOR:_id++,
  POWER_NODE:_id++,LARGE_POWER_NODE:_id++,SURGE_TOWER:_id++,BATTERY:_id++,LARGE_BATTERY:_id++,
  COMBUSTION:_id++,THERMAL_GEN:_id++,STEAM_GEN:_id++,DIFF_GEN:_id++,RTG:_id++,SOLAR:_id++,LARGE_SOLAR:_id++,
  THORIUM_REACTOR:_id++,IMPACT_REACTOR:_id++,
  GRAPHITE_PRESS:_id++,MULTI_PRESS:_id++,SILICON_SMELTER:_id++,SILICON_CRUCIBLE:_id++,KILN:_id++,
  PLASTANIUM_COMPRESSOR:_id++,PHASE_WEAVER:_id++,SURGE_SMELTER:_id++,CRYOFLUID_MIXER:_id++,
  PYRATITE_MIXER:_id++,BLAST_MIXER:_id++,MELTER:_id++,SEPARATOR:_id++,DISASSEMBLER:_id++,
  SPORE_PRESS:_id++,PULVERIZER:_id++,COAL_CENTRIFUGE:_id++,INCINERATOR:_id++,
  COPPER_WALL:_id++,COPPER_WALL_L:_id++,TITANIUM_WALL:_id++,TITANIUM_WALL_L:_id++,
  THORIUM_WALL:_id++,THORIUM_WALL_L:_id++,PHASE_WALL:_id++,PHASE_WALL_L:_id++,
  SURGE_WALL:_id++,SURGE_WALL_L:_id++,DOOR:_id++,
  DUO:_id++,SCORCH:_id++,HAIL:_id++,ARC:_id++,SCATTER:_id++,WAVE:_id++,LANCER:_id++,
  PARALLAX:_id++,SWARMER:_id++,SALVO:_id++,SEGMENT:_id++,TSUNAMI:_id++,FUSE:_id++,
  RIPPLE:_id++,CYCLONE:_id++,FORESHADOW:_id++,SPECTRE:_id++,MELTDOWN:_id++,
  MENDER:_id++,MEND_PROJECTOR:_id++,OVERDRIVE:_id++,OVERDRIVE_DOME:_id++,FORCE_PROJECTOR:_id++,
  SHOCK_MINE:_id++,ILLUMINATOR:_id++,
  GROUND_FACTORY:_id++,AIR_FACTORY:_id++,NAVAL_FACTORY:_id++,
  ADDITIVE_RECON:_id++,MULTIPLICATIVE_RECON:_id++,EXPONENTIAL_RECON:_id++,TETRATIVE_RECON:_id++,
  REPAIR_POINT:_id++,REPAIR_TURRET:_id++
};
function def(o){return Object.assign({size:1,itemCap:10,liqCap:60,powerUse:0,powerGen:0,directional:false,category:'factory',health:100,desc:''},o)}
const BUILDING_DEFS={
  [BTYPE.CONVEYOR]:def({name:'Конвейер',size:1,color:'#8a8a8a',speed:.08,directional:true,category:'transport',health:45}),
  [BTYPE.TITANIUM_CONVEYOR]:def({name:'Титан. конв.',size:1,color:'#8da1b0',speed:.16,directional:true,category:'transport',health:65}),
  [BTYPE.PLASTANIUM_CONVEYOR]:def({name:'Пластан. конв.',size:1,color:'#9eff7a',speed:.06,directional:true,category:'transport',health:75}),
  [BTYPE.ARMORED_CONVEYOR]:def({name:'Брон. конв.',size:1,color:'#6a7a8a',speed:.12,directional:true,category:'transport',health:180}),
  [BTYPE.JUNCTION]:def({name:'Перекресток',size:1,color:'#666',category:'transport',health:50}),
  [BTYPE.BRIDGE]:def({name:'Мост',size:1,color:'#a08040',range:3,directional:true,category:'transport',health:50}),
  [BTYPE.PHASE_BRIDGE]:def({name:'Фаз. мост',size:1,color:'#c77dff',range:15,directional:true,category:'transport',health:60}),
  [BTYPE.ROUTER]:def({name:'Маршрутизатор',size:1,color:'#cc8844',category:'transport',health:50}),
  [BTYPE.DISTRIBUTOR]:def({name:'Распределитель',size:2,color:'#cc8844',category:'transport',health:130}),
  [BTYPE.SORTER]:def({name:'Сортировщик',size:1,color:'#44aa88',category:'transport',health:50}),
  [BTYPE.INV_SORTER]:def({name:'Инв. сортир.',size:1,color:'#aa4488',category:'transport',health:50}),
  [BTYPE.GATE]:def({name:'Затвор',size:1,color:'#888844',category:'transport',health:50}),
  [BTYPE.INV_GATE]:def({name:'Инв. затвор',size:1,color:'#884488',category:'transport',health:50}),
  [BTYPE.UNLOADER]:def({name:'Разгрузчик',size:1,color:'#6ab0ff',category:'transport',health:50}),
  [BTYPE.MASS_DRIVER]:def({name:'Катапульта',size:3,color:'#6a5a8a',itemCap:20,powerUse:105,category:'transport',health:450,range:55}),
  [BTYPE.CONTAINER]:def({name:'Контейнер',size:2,color:'#7a6a5a',itemCap:80,category:'transport',health:300}),
  [BTYPE.VAULT]:def({name:'Хранилище',size:3,color:'#6a5a4a',itemCap:300,category:'transport',health:700}),
  [BTYPE.MECH_DRILL]:def({name:'Мех. бур',size:2,color:'#8a7050',itemCap:10,liqCap:30,category:'drill',health:160,mine:{sand:.4,copper:.36,lead:.36,coal:.34},boostWater:3,boostMul:2.56}),
  [BTYPE.PNEU_DRILL]:def({name:'Пневм. бур',size:2,color:'#6a8a9a',itemCap:10,liqCap:35,category:'drill',health:200,mine:{sand:.6,copper:.53,lead:.53,coal:.48,titanium:.43},boostWater:5,boostMul:2.56}),
  [BTYPE.LASER_DRILL]:def({name:'Лазер. бур',size:3,color:'#6a90b0',itemCap:20,liqCap:40,powerUse:66,category:'drill',health:320,mine:{sand:1,copper:.9,lead:.9,coal:.8,titanium:.7,thorium:.6},boostWater:6,boostMul:2.56}),
  [BTYPE.AIRBLAST_DRILL]:def({name:'Воздуш. бур',size:4,color:'#5a80a0',itemCap:30,liqCap:50,powerUse:180,category:'drill',health:480,mine:{sand:1.6,copper:1.4,lead:1.4,coal:1.2,titanium:1,thorium:.85},boostWater:8,boostMul:3.24}),
  [BTYPE.CONDUIT]:def({name:'Труба',size:1,color:'#4a90d0',category:'liquid',health:40}),
  [BTYPE.PULSE_CONDUIT]:def({name:'Имп. труба',size:1,color:'#6ab0ff',category:'liquid',health:50}),
  [BTYPE.PLATED_CONDUIT]:def({name:'Брон. труба',size:1,color:'#5a80a0',category:'liquid',health:120}),
  [BTYPE.LIQUID_ROUTER]:def({name:'Жидк. маршр.',size:1,color:'#3a70b0',category:'liquid',health:50}),
  [BTYPE.LIQUID_JUNCTION]:def({name:'Жидк. перекр.',size:1,color:'#2a5080',category:'liquid',health:50}),
  [BTYPE.LIQUID_BRIDGE]:def({name:'Жидк. мост',size:1,color:'#5aa0c0',range:3,directional:true,category:'liquid',health:50}),
  [BTYPE.PHASE_CONDUIT]:def({name:'Фаз. труба',size:1,color:'#a070ff',range:15,directional:true,category:'liquid',health:60}),
  [BTYPE.TANK]:def({name:'Цистерна',size:2,color:'#3a6080',liqCap:700,itemCap:0,category:'liquid',health:250}),
  [BTYPE.LARGE_TANK]:def({name:'Больш. цистерна',size:3,color:'#2a5070',liqCap:1800,itemCap:0,category:'liquid',health:500}),
  [BTYPE.MECH_PUMP]:def({name:'Мех. помпа',size:1,color:'#4a80b0',liqCap:40,pumpRate:7,category:'liquid',health:60}),
  [BTYPE.ROTARY_PUMP]:def({name:'Ротор. помпа',size:2,color:'#5a90c0',liqCap:80,powerUse:12,pumpRate:48,category:'liquid',health:120}),
  [BTYPE.THERMAL_PUMP]:def({name:'Терм. помпа',size:3,color:'#6aa0d0',liqCap:200,powerUse:78,pumpRate:118,category:'liquid',health:200}),
  [BTYPE.WATER_EXTRACTOR]:def({name:'Гидронасос',size:2,color:'#40a0c0',liqCap:40,powerUse:90,category:'liquid',health:100}),
  [BTYPE.OIL_EXTRACTOR]:def({name:'Нефт. вышка',size:2,color:'#2a1a0a',liqCap:40,itemCap:10,powerUse:180,category:'liquid',health:150}),
  [BTYPE.CULTIVATOR]:def({name:'Культиватор',size:2,color:'#50a040',liqCap:60,itemCap:10,powerUse:80,category:'liquid',health:120}),
  [BTYPE.POWER_NODE]:def({name:'Силовой узел',size:1,color:'#e0c040',powerRange:6,category:'power',health:40}),
  [BTYPE.LARGE_POWER_NODE]:def({name:'Больш. узел',size:2,color:'#e0b030',powerRange:15,category:'power',health:80}),
  [BTYPE.SURGE_TOWER]:def({name:'Кинет. вышка',size:1,color:'#f3e03b',powerRange:40,category:'power',health:100}),
  [BTYPE.BATTERY]:def({name:'Аккумулятор',size:1,color:'#60c060',powerCap:4000,category:'power',health:80}),
  [BTYPE.LARGE_BATTERY]:def({name:'Больш. аккум.',size:2,color:'#50b050',powerCap:50000,category:'power',health:160}),
  [BTYPE.COMBUSTION]:def({name:'ДВС',size:1,color:'#c07040',itemCap:10,powerGen:60,category:'power',health:80}),
  [BTYPE.THERMAL_GEN]:def({name:'Терм. ген.',size:2,color:'#d06030',powerGen:108,category:'power',health:180}),
  [BTYPE.STEAM_GEN]:def({name:'Паровой ген.',size:2,color:'#a0b0c0',liqCap:60,itemCap:10,powerGen:330,category:'power',health:200}),
  [BTYPE.DIFF_GEN]:def({name:'Дифф. ген.',size:3,color:'#80d0e0',liqCap:60,itemCap:10,powerGen:1080,category:'power',health:400}),
  [BTYPE.RTG]:def({name:'РТГ',size:2,color:'#c0a0d0',itemCap:10,powerGen:270,category:'power',health:300}),
  [BTYPE.SOLAR]:def({name:'Солн. панель',size:1,color:'#4060a0',powerGen:7.2,category:'power',health:40}),
  [BTYPE.LARGE_SOLAR]:def({name:'Больш. солн.',size:3,color:'#3050a0',powerGen:96,category:'power',health:150}),
  [BTYPE.THORIUM_REACTOR]:def({name:'Ториевый ре.',size:3,color:'#e090c0',liqCap:30,itemCap:30,powerGen:900,category:'power',health:600}),
  [BTYPE.IMPACT_REACTOR]:def({name:'Импульс. ре.',size:4,color:'#ff60a0',liqCap:80,itemCap:10,powerUse:1500,powerGen:7800,category:'power',health:900}),
  [BTYPE.GRAPHITE_PRESS]:def({name:'Графит. пресс',size:2,color:'#707070',itemCap:10,category:'factory',health:160,recipe:{in:{coal:2},out:{graphite:1},time:1.5}}),
  [BTYPE.MULTI_PRESS]:def({name:'Улучш. пресс',size:3,color:'#606060',liqCap:60,itemCap:20,powerUse:108,category:'factory',health:300,recipe:{in:{coal:3,water:6},out:{graphite:2},time:.5}}),
  [BTYPE.SILICON_SMELTER]:def({name:'Кремн. плав.',size:2,color:'#a0a0b0',itemCap:10,powerUse:30,category:'factory',health:160,recipe:{in:{coal:1,sand:2},out:{silicon:1},time:.666}}),
  [BTYPE.SILICON_CRUCIBLE]:def({name:'Кремн. тигель',size:3,color:'#9090a0',itemCap:30,powerUse:240,category:'factory',health:300,recipe:{in:{coal:4,sand:6,pyratite:1},out:{silicon:8},time:5.333}}),
  [BTYPE.KILN]:def({name:'Печь',size:2,color:'#c08040',itemCap:10,powerUse:36,category:'factory',health:160,recipe:{in:{lead:1,sand:1},out:{metaglass:1},time:.5}}),
  [BTYPE.PLASTANIUM_COMPRESSOR]:def({name:'Пластан. компр.',size:2,color:'#80c060',liqCap:60,itemCap:10,powerUse:180,category:'factory',health:200,recipe:{in:{oil:15,titanium:2},out:{plastanium:1},time:1}}),
  [BTYPE.PHASE_WEAVER]:def({name:'Фазовый ткач',size:2,color:'#b080e0',itemCap:10,powerUse:300,category:'factory',health:200,recipe:{in:{thorium:4,sand:10},out:{phase:1},time:2}}),
  [BTYPE.SURGE_SMELTER]:def({name:'Кинет. плав.',size:3,color:'#e0c040',itemCap:20,powerUse:240,category:'factory',health:300,recipe:{in:{copper:3,lead:4,titanium:2,silicon:3},out:{surge:1},time:1.25}}),
  [BTYPE.CRYOFLUID_MIXER]:def({name:'Мешалка крио',size:2,color:'#60d0e0',liqCap:36,itemCap:10,powerUse:60,category:'factory',health:160,recipe:{in:{titanium:1,water:12},out:{cryo:12},time:2}}),
  [BTYPE.PYRATITE_MIXER]:def({name:'Мешалка пирот.',size:2,color:'#e06040',itemCap:10,powerUse:12,category:'factory',health:160,recipe:{in:{coal:1,lead:2,sand:2},out:{pyratite:1},time:.75}}),
  [BTYPE.BLAST_MIXER]:def({name:'Мешалка взрыв.',size:2,color:'#e04060',itemCap:10,powerUse:24,category:'factory',health:160,recipe:{in:{pyratite:1,spore:1},out:{blast:1},time:.75}}),
  [BTYPE.MELTER]:def({name:'Плавильня',size:1,color:'#ff8040',liqCap:10,itemCap:10,powerUse:60,category:'factory',health:100,recipe:{in:{metalom:1},out:{slag:12},time:.166}}),
  [BTYPE.SEPARATOR]:def({name:'Отделитель',size:2,color:'#a08060',liqCap:40,powerUse:66,category:'factory',health:160}),
  [BTYPE.DISASSEMBLER]:def({name:'Разборщик',size:3,color:'#908070',liqCap:72,itemCap:20,powerUse:240,category:'factory',health:300}),
  [BTYPE.SPORE_PRESS]:def({name:'Спор. пресс',size:2,color:'#60a040',liqCap:60,powerUse:42,category:'factory',health:160,recipe:{in:{spore:1},out:{oil:18},time:.333}}),
  [BTYPE.PULVERIZER]:def({name:'Измельчитель',size:1,color:'#a09070',itemCap:10,powerUse:30,category:'factory',health:80,recipe:{in:{metalom:1},out:{sand:1},time:.666}}),
  [BTYPE.COAL_CENTRIFUGE]:def({name:'Угольн. центриф.',size:2,color:'#505050',liqCap:60,powerUse:42,category:'factory',health:160,recipe:{in:{oil:6},out:{coal:1},time:.5}}),
  [BTYPE.INCINERATOR]:def({name:'Мусоросжиг.',size:1,color:'#404040',powerUse:30,category:'factory',health:80}),
  [BTYPE.COPPER_WALL]:def({name:'Медн. стена',size:1,color:'#c08050',category:'walls',health:320}),
  [BTYPE.COPPER_WALL_L]:def({name:'Больш. медн.',size:2,color:'#c08050',category:'walls',health:1280}),
  [BTYPE.TITANIUM_WALL]:def({name:'Титан. стена',size:1,color:'#8da1b0',category:'walls',health:560}),
  [BTYPE.TITANIUM_WALL_L]:def({name:'Больш. титан.',size:2,color:'#8da1b0',category:'walls',health:2240}),
  [BTYPE.THORIUM_WALL]:def({name:'Ториевая стена',size:1,color:'#f9a3c7',category:'walls',health:800}),
  [BTYPE.THORIUM_WALL_L]:def({name:'Больш. ториев.',size:2,color:'#f9a3c7',category:'walls',health:3200}),
  [BTYPE.PHASE_WALL]:def({name:'Фаз. стена',size:1,color:'#c77dff',category:'walls',health:600}),
  [BTYPE.PHASE_WALL_L]:def({name:'Больш. фаз.',size:2,color:'#c77dff',category:'walls',health:2400}),
  [BTYPE.SURGE_WALL]:def({name:'Кинет. стена',size:1,color:'#f3e03b',category:'walls',health:920}),
  [BTYPE.SURGE_WALL_L]:def({name:'Больш. кинет.',size:2,color:'#f3e03b',category:'walls',health:3680}),
  [BTYPE.DOOR]:def({name:'Дверь',size:1,color:'#888',category:'walls',health:400}),
  [BTYPE.DUO]:def({name:'Двойная',size:1,color:'#8a9aaa',category:'turret',health:250,range:18,reload:.35,damage:12,ammo:['copper','graphite','silicon']}),
  [BTYPE.SCORCH]:def({name:'Обжигатель',size:1,color:'#e07030',category:'turret',health:280,range:10,reload:.08,damage:8,ammo:['coal','pyratite']}),
  [BTYPE.HAIL]:def({name:'Град',size:1,color:'#6a8a6a',category:'turret',health:260,range:28,reload:1.2,damage:25,ammo:['graphite','silicon','pyratite']}),
  [BTYPE.ARC]:def({name:'Дуга',size:1,color:'#60d0ff',category:'turret',health:220,range:14,reload:.4,damage:18,powerUse:18}),
  [BTYPE.SCATTER]:def({name:'Рассеиватель',size:2,color:'#7a9a7a',category:'turret',health:400,range:26,reload:.5,damage:15,ammo:['lead','metaglass']}),
  [BTYPE.WAVE]:def({name:'Волна',size:2,color:'#4da6ff',category:'turret',health:450,range:20,reload:.6,damage:20,liqAmmo:['water','slag','cryo','oil']}),
  [BTYPE.LANCER]:def({name:'Копейщик',size:2,color:'#70c0ff',category:'turret',health:420,range:22,reload:1.5,damage:80,powerUse:36}),
  [BTYPE.PARALLAX]:def({name:'Параллакс',size:2,color:'#a080d0',category:'turret',health:380,range:20,reload:.1,damage:5,powerUse:18}),
  [BTYPE.SWARMER]:def({name:'Роевик',size:2,color:'#d08040',category:'turret',health:450,range:24,reload:.3,damage:14,ammo:['blast','pyratite','surge']}),
  [BTYPE.SALVO]:def({name:'Залп',size:2,color:'#8a9aaa',category:'turret',health:500,range:22,reload:.6,damage:20,ammo:['copper','graphite','pyratite','silicon']}),
  [BTYPE.SEGMENT]:def({name:'Сегмент',size:2,color:'#60e0ff',category:'turret',health:400,range:24,reload:.2,damage:10,powerUse:48}),
  [BTYPE.TSUNAMI]:def({name:'Цунами',size:3,color:'#4da6ff',category:'turret',health:700,range:28,reload:.4,damage:30,liqAmmo:['water','slag','cryo','oil']}),
  [BTYPE.FUSE]:def({name:'Взрыватель',size:3,color:'#c0a060',category:'turret',health:650,range:14,reload:.8,damage:50,ammo:['titanium','thorium']}),
  [BTYPE.RIPPLE]:def({name:'Рябь',size:3,color:'#7a9a7a',category:'turret',health:700,range:40,reload:1.5,damage:40,ammo:['graphite','silicon','plastanium','blast']}),
  [BTYPE.CYCLONE]:def({name:'Циклон',size:3,color:'#d08050',category:'turret',health:800,range:26,reload:.2,damage:18,ammo:['metaglass','blast','plastanium','surge']}),
  [BTYPE.FORESHADOW]:def({name:'Знамение',size:4,color:'#e0e0f0',category:'turret',health:1000,range:55,reload:3,damage:200,ammo:['surge'],powerUse:60}),
  [BTYPE.SPECTRE]:def({name:'Спектр',size:4,color:'#c04040',category:'turret',health:1200,range:28,reload:.15,damage:30,ammo:['graphite','thorium','pyratite','surge']}),
  [BTYPE.MELTDOWN]:def({name:'Испепелитель',size:4,color:'#ff4040',category:'turret',health:1100,range:24,reload:.05,damage:15,powerUse:120,liqAmmo:['cryo']}),
  [BTYPE.MENDER]:def({name:'Ремонтник',size:1,color:'#60d080',category:'factory',health:80,powerUse:12,range:5,heal:8}),
  [BTYPE.MEND_PROJECTOR]:def({name:'Рем. проектор',size:2,color:'#50c070',category:'factory',health:160,powerUse:60,range:10,heal:20}),
  [BTYPE.OVERDRIVE]:def({name:'Ускоритель',size:2,color:'#e0c040',category:'factory',health:180,powerUse:90,range:8,boost:1.25}),
  [BTYPE.OVERDRIVE_DOME]:def({name:'Купол ускор.',size:3,color:'#e0b020',category:'factory',health:300,powerUse:180,range:14,boost:1.5}),
  [BTYPE.FORCE_PROJECTOR]:def({name:'Силовой купол',size:3,color:'#60a0ff',category:'factory',health:400,powerUse:180,range:12,shield:1000}),
  [BTYPE.SHOCK_MINE]:def({name:'Мина',size:1,color:'#a04040',category:'factory',health:40,damage:60}),
  [BTYPE.ILLUMINATOR]:def({name:'Фонарь',size:1,color:'#ffffa0',category:'factory',health:40,powerUse:3}),
  [BTYPE.GROUND_FACTORY]:def({name:'Наземн. завод',size:3,color:'#8a7050',category:'units',health:500,powerUse:72,itemCap:20,unitType:'dagger',unitTime:15,unitCost:{lead:10,silicon:10}}),
  [BTYPE.AIR_FACTORY]:def({name:'Воздушн. завод',size:3,color:'#6a8aaa',category:'units',health:500,powerUse:72,itemCap:20,unitType:'flare',unitTime:15,unitCost:{copper:15,silicon:15}}),
  [BTYPE.NAVAL_FACTORY]:def({name:'Морской завод',size:3,color:'#4a80a0',category:'units',health:500,powerUse:72,itemCap:20,unitType:'risso',unitTime:20,unitCost:{metaglass:20,silicon:15}}),
  [BTYPE.ADDITIVE_RECON]:def({name:'Адд. реконстр.',size:3,color:'#7a6a5a',category:'units',health:600,powerUse:90,unitTime:20}),
  [BTYPE.MULTIPLICATIVE_RECON]:def({name:'Мульт. реконстр.',size:5,color:'#6a5a4a',category:'units',health:900,powerUse:180,unitTime:40}),
  [BTYPE.EXPONENTIAL_RECON]:def({name:'Эксп. реконстр.',size:7,color:'#5a4a3a',category:'units',health:1400,powerUse:360,unitTime:70}),
  [BTYPE.TETRATIVE_RECON]:def({name:'Тетр. реконстр.',size:9,color:'#4a3a2a',category:'units',health:2000,powerUse:600,unitTime:120}),
  [BTYPE.REPAIR_POINT]:def({name:'Рем. точка',size:1,color:'#60d0a0',category:'units',health:80,powerUse:18,range:8,heal:12}),
  [BTYPE.REPAIR_TURRET]:def({name:'Рем. турель',size:2,color:'#50c090',category:'units',health:200,powerUse:48,range:14,heal:30})
};
const UNIT_DEFS={
  dagger:{name:'Dagger',hp:140,speed:1.2,damage:12,range:12,color:'#c08050',size:10},
  crawler:{name:'Crawler',hp:80,speed:1.5,damage:40,range:2,color:'#6a5a40',size:8},
  nova:{name:'Nova',hp:120,speed:1.1,damage:10,range:14,color:'#80d0a0',size:10},
  flare:{name:'Flare',hp:70,speed:2.0,damage:9,range:16,color:'#8a9aaa',size:8,flying:true},
  mono:{name:'Mono',hp:50,speed:1.4,damage:0,range:0,color:'#d0d060',size:8,flying:true,miner:true},
  risso:{name:'Risso',hp:180,speed:1.0,damage:15,range:18,color:'#5a90b0',size:12,naval:true},
  enemy:{name:'Враг',hp:80,speed:.8,damage:8,range:10,color:'#e04040',size:9}
};
const CAT_MAP={factory:[],units:[],logic:[],power:[],walls:[],transport:[],liquid:[],drill:[],turret:[]};
for(const [k,v] of Object.entries(BUILDING_DEFS)){
  const cat=v.category||'factory';
  if(CAT_MAP[cat])CAT_MAP[cat].push(+k);
  else CAT_MAP.factory.push(+k);
}
const CATEGORIES=[
  {id:'factory',name:'Заводы',side:'left',row:0,blocks:CAT_MAP.factory},
  {id:'units',name:'Юниты',side:'right',row:0,blocks:CAT_MAP.units},
  {id:'power',name:'Энергия',side:'left',row:1,blocks:CAT_MAP.power},
  {id:'walls',name:'Стены',side:'right',row:1,blocks:CAT_MAP.walls},
  {id:'transport',name:'Транспорт',side:'left',row:2,blocks:CAT_MAP.transport},
  {id:'liquid',name:'Жидкости',side:'right',row:2,blocks:CAT_MAP.liquid},
  {id:'drill',name:'Буры',side:'left',row:3,blocks:CAT_MAP.drill},
  {id:'turret',name:'Турели',side:'right',row:3,blocks:CAT_MAP.turret}
];
